networks:
  app_network:
    driver: bridge

volumes:
  db_data:

services:
  app:
    build: 
      context: ./
    ports:
      - 80:80
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@database:3306/database
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: mysql
    env_file:
      - .env.database
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: always
